apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapi-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: demoapi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoapi
            port:
              number: 80
